import type { PlayerSeedTemplate } from "../../types/seed";

export const PLAYER_SEED_TEMPLATES = [
  {
    "name": "Facundo Colidio",
    "position": "LW",
    "marketValueM": "6.00",
    "dateOfBirth": "2000-01-04",
    "heightCm": 179,
    "weightKg": 68,
    "preferredFoot": "Right",
    "nationality": "Argentina",
    "teamName": "River Plate",
    "debutYear": 2022,
    "fotmobPlayerImageId": 949735
  },
  {
    "name": "Lucas Martínez Quarta",
    "position": "CB",
    "marketValueM": "9.00",
    "dateOfBirth": "1996-05-10",
    "heightCm": 183,
    "weightKg": 79,
    "preferredFoot": "Right",
    "nationality": "Argentina",
    "teamName": "River Plate",
    "debutYear": 2016,
    "fotmobPlayerImageId": 638771
  },
  {
    "name": "Pablo Solari",
    "position": "LW",
    "marketValueM": "7.00",
    "dateOfBirth": "2001-10-18",
    "heightCm": 180,
    "weightKg": 75,
    "preferredFoot": "Right",
    "nationality": "Argentina",
    "teamName": "River Plate",
    "debutYear": 2021,
    "fotmobPlayerImageId": 1201406
  },
  {
    "name": "Sebastián Driussi",
    "position": "CF",
    "marketValueM": "4.50",
    "dateOfBirth": "1996-02-09",
    "heightCm": 175,
    "weightKg": 70,
    "preferredFoot": "Both",
    "nationality": "Argentina",
    "teamName": "River Plate",
    "debutYear": 2013,
    "fotmobPlayerImageId": 510698
  },
  {
    "name": "Gonzalo Montiel",
    "position": "RB",
    "marketValueM": "4.50",
    "dateOfBirth": "1997-01-01",
    "heightCm": 177,
    "weightKg": 72,
    "preferredFoot": "Right",
    "nationality": "Argentina",
    "teamName": "River Plate",
    "debutYear": 2016,
    "fotmobPlayerImageId": 687008
  },
  {
    "name": "Miguel Merentiel",
    "position": "CF",
    "marketValueM": "8.00",
    "dateOfBirth": "1996-02-24",
    "heightCm": 176,
    "weightKg": 70,
    "preferredFoot": "Right",
    "nationality": "Uruguay",
    "teamName": "Boca Juniors",
    "debutYear": 2023,
    "fotmobPlayerImageId": 826418
  },
  {
    "name": "Kevin Zenón",
    "position": "LW",
    "marketValueM": "4.40",
    "dateOfBirth": "2001-07-30",
    "heightCm": 181,
    "weightKg": 72,
    "preferredFoot": "Left",
    "nationality": "Argentina",
    "teamName": "Boca Juniors",
    "debutYear": 2023,
    "fotmobPlayerImageId": 1201039
  },
  {
    "name": "Cristian Medina",
    "position": "CM",
    "marketValueM": "8.00",
    "dateOfBirth": "2001-06-18",
    "heightCm": 178,
    "weightKg": 72,
    "preferredFoot": "Right",
    "nationality": "Argentina",
    "teamName": "Boca Juniors",
    "debutYear": 2020,
    "fotmobPlayerImageId": 1199960
  },
  {
    "name": "Exequiel Zeballos",
    "position": "LW",
    "marketValueM": "7.00",
    "dateOfBirth": "2002-04-24",
    "heightCm": 172,
    "weightKg": 65,
    "preferredFoot": "Right",
    "nationality": "Argentina",
    "teamName": "Boca Juniors",
    "debutYear": 2020,
    "fotmobPlayerImageId": 1110044
  },
  {
    "name": "Leandro Brey",
    "position": "GK",
    "marketValueM": "3.00",
    "dateOfBirth": "2000-08-07",
    "heightCm": 191,
    "weightKg": 84,
    "preferredFoot": "Right",
    "nationality": "Argentina",
    "teamName": "Boca Juniors",
    "debutYear": 2022,
    "fotmobPlayerImageId": 1201672
  },
  {
    "name": "Marco Di Césare",
    "position": "CB",
    "marketValueM": "9.00",
    "dateOfBirth": "2002-01-30",
    "heightCm": 186,
    "weightKg": 82,
    "preferredFoot": "Right",
    "nationality": "Argentina",
    "teamName": "Racing Club",
    "debutYear": 2021,
    "fotmobPlayerImageId": 1209398
  },
  {
    "name": "Juan Nardoni",
    "position": "CM",
    "marketValueM": "11.00",
    "dateOfBirth": "2002-05-21",
    "heightCm": 183,
    "weightKg": 78,
    "preferredFoot": "Right",
    "nationality": "Argentina",
    "teamName": "Racing Club",
    "debutYear": 2021,
    "fotmobPlayerImageId": 1087773
  },
  {
    "name": "Santiago Sosa",
    "position": "CDM",
    "marketValueM": "8.00",
    "dateOfBirth": "1999-05-03",
    "heightCm": 182,
    "weightKg": 78,
    "preferredFoot": "Right",
    "nationality": "Argentina",
    "teamName": "Racing Club",
    "debutYear": 2018,
    "fotmobPlayerImageId": 958860
  },
  {
    "name": "Ezequiel Unsain",
    "position": "GK",
    "marketValueM": "4.00",
    "dateOfBirth": "1995-06-28",
    "heightCm": 189,
    "weightKg": 83,
    "preferredFoot": "Right",
    "nationality": "Argentina",
    "teamName": "Racing Club",
    "debutYear": 2016,
    "fotmobPlayerImageId": 723492
  },
  {
    "name": "Gabriel Rojas",
    "position": "RB",
    "marketValueM": "5.00",
    "dateOfBirth": "1997-02-25",
    "heightCm": 174,
    "weightKg": 70,
    "preferredFoot": "Right",
    "nationality": "Argentina",
    "teamName": "Racing Club",
    "debutYear": 2018,
    "fotmobPlayerImageId": 805540
  },
  {
    "name": "Kevin Lomónaco",
    "position": "CB",
    "marketValueM": "12.00",
    "dateOfBirth": "2002-01-08",
    "heightCm": 187,
    "weightKg": 81,
    "preferredFoot": "Right",
    "nationality": "Argentina",
    "teamName": "Independiente",
    "debutYear": 2021,
    "fotmobPlayerImageId": 1206583
  },
  {
    "name": "Luciano Cabral",
    "position": "CAM",
    "marketValueM": "4.50",
    "dateOfBirth": "2000-03-15",
    "heightCm": 175,
    "weightKg": 70,
    "preferredFoot": "Left",
    "nationality": "Argentina",
    "teamName": "Independiente",
    "debutYear": 2020,
    "fotmobPlayerImageId": 527862
  },
  {
    "name": "Ignacio Pussetto",
    "position": "RW",
    "marketValueM": "4.00",
    "dateOfBirth": "1997-03-25",
    "heightCm": 172,
    "weightKg": 69,
    "preferredFoot": "Right",
    "nationality": "Argentina",
    "teamName": "Independiente",
    "debutYear": 2016,
    "fotmobPlayerImageId": 470847
  },
  {
    "name": "Iván Marcone",
    "position": "CDM",
    "marketValueM": "2.50",
    "dateOfBirth": "1992-06-17",
    "heightCm": 181,
    "weightKg": 77,
    "preferredFoot": "Right",
    "nationality": "Argentina",
    "teamName": "Independiente",
    "debutYear": 2012,
    "fotmobPlayerImageId": 157868
  },
  {
    "name": "Gabriel Ávalos",
    "position": "CF",
    "marketValueM": "3.50",
    "dateOfBirth": "1995-04-27",
    "heightCm": 180,
    "weightKg": 75,
    "preferredFoot": "Right",
    "nationality": "Paraguay",
    "teamName": "Independiente",
    "debutYear": 2015,
    "fotmobPlayerImageId": 576154
  },
  {
    "name": "Lucas Zelarayán",
    "position": "CAM",
    "marketValueM": "4.50",
    "dateOfBirth": "1992-06-20",
    "heightCm": 172,
    "weightKg": 70,
    "preferredFoot": "Right",
    "nationality": "Armenia",
    "teamName": "Belgrano",
    "debutYear": 2011,
    "fotmobPlayerImageId": 322965
  },
  {
    "name": "Emiliano Rigoni",
    "position": "LW",
    "marketValueM": "1.50",
    "dateOfBirth": "1993-02-04",
    "heightCm": 180,
    "weightKg": 74,
    "preferredFoot": "Both",
    "nationality": "Argentina",
    "teamName": "Belgrano",
    "debutYear": 2013,
    "fotmobPlayerImageId": 371543
  },
  {
    "name": "Lisandro López",
    "position": "CB",
    "marketValueM": "0.80",
    "dateOfBirth": "1989-09-01",
    "heightCm": 188,
    "weightKg": 80,
    "preferredFoot": "Right",
    "nationality": "Argentina",
    "teamName": "Belgrano",
    "debutYear": 2010,
    "fotmobPlayerImageId": 182456
  },
  {
    "name": "Lucas Passerini",
    "position": "CF",
    "marketValueM": "1.20",
    "dateOfBirth": "1994-09-12",
    "heightCm": 189,
    "weightKg": 82,
    "preferredFoot": "Right",
    "nationality": "Argentina",
    "teamName": "Belgrano",
    "debutYear": 2016,
    "fotmobPlayerImageId": 564614
  },
  {
    "name": "Thiago Cardozo",
    "position": "GK",
    "marketValueM": "2.50",
    "dateOfBirth": "1995-10-17",
    "heightCm": 183,
    "weightKg": 84,
    "preferredFoot": "Right",
    "nationality": "Uruguay",
    "teamName": "Belgrano",
    "debutYear": 2017,
    "fotmobPlayerImageId": 643566
  },
  {
    "name": "Guido Herrera",
    "position": "GK",
    "marketValueM": "2.50",
    "dateOfBirth": "1991-08-25",
    "heightCm": 192,
    "weightKg": 87,
    "preferredFoot": "Right",
    "nationality": "Argentina",
    "teamName": "Talleres (C)",
    "debutYear": 2013,
    "fotmobPlayerImageId": 358714
  },
  {
    "name": "Matías Galarza",
    "position": "CDM",
    "marketValueM": "4.00",
    "dateOfBirth": "2002-03-04",
    "heightCm": 180,
    "weightKg": 72,
    "preferredFoot": "Right",
    "nationality": "Argentina",
    "teamName": "Talleres (C)",
    "debutYear": 2022,
    "fotmobPlayerImageId": 1277340
  },
  {
    "name": "José Luis Palomino",
    "position": "CB",
    "marketValueM": "1.00",
    "dateOfBirth": "1990-01-05",
    "heightCm": 183,
    "weightKg": 79,
    "preferredFoot": "Left",
    "nationality": "Argentina",
    "teamName": "Talleres (C)",
    "debutYear": 2010,
    "fotmobPlayerImageId": 185625
  },
  {
    "name": "Valentín Dávila",
    "position": "RW",
    "marketValueM": "3.50",
    "dateOfBirth": "2006-07-14",
    "heightCm": 174,
    "weightKg": 68,
    "preferredFoot": "Left",
    "nationality": "Argentina",
    "teamName": "Talleres (C)",
    "debutYear": 2025,
    "fotmobPlayerImageId": 1695460
  },
  {
    "name": "Ronaldo Martínez",
    "position": "CF",
    "marketValueM": "3.50",
    "dateOfBirth": "1996-04-25",
    "heightCm": 178,
    "weightKg": 72,
    "preferredFoot": "Right",
    "nationality": "Paraguay",
    "teamName": "Talleres (C)",
    "debutYear": 2023,
    "fotmobPlayerImageId": 659738
  },
  {
    "name": "Emanuel Bilbao",
    "position": "GK",
    "marketValueM": "0.80",
    "dateOfBirth": "1993-01-22",
    "heightCm": 188,
    "weightKg": 82,
    "preferredFoot": "Right",
    "nationality": "Argentina",
    "teamName": "Instituto (C)",
    "debutYear": 2014,
    "fotmobPlayerImageId": 501425
  },
  {
    "name": "Alex Luna",
    "position": "CF",
    "marketValueM": "1.50",
    "dateOfBirth": "1996-05-22",
    "heightCm": 177,
    "weightKg": 73,
    "preferredFoot": "Right",
    "nationality": "Argentina",
    "teamName": "Instituto (C)",
    "debutYear": 2018,
    "fotmobPlayerImageId": 1314218
  },
  {
    "name": "Giuliano Cerato",
    "position": "RB",
    "marketValueM": "1.20",
    "dateOfBirth": "2001-09-11",
    "heightCm": 174,
    "weightKg": 68,
    "preferredFoot": "Right",
    "nationality": "Argentina",
    "teamName": "Instituto (C)",
    "debutYear": 2021,
    "fotmobPlayerImageId": 1098253
  },
  {
    "name": "Ignacio Méndez",
    "position": "CAM",
    "marketValueM": "2.00",
    "dateOfBirth": "2001-04-12",
    "heightCm": 175,
    "weightKg": 69,
    "preferredFoot": "Left",
    "nationality": "Argentina",
    "teamName": "Instituto (C)",
    "debutYear": 2022,
    "fotmobPlayerImageId": 1207421
  },
  {
    "name": "Diego Sosa",
    "position": "CB",
    "marketValueM": "1.00",
    "dateOfBirth": "1993-06-30",
    "heightCm": 185,
    "weightKg": 80,
    "preferredFoot": "Right",
    "nationality": "Argentina",
    "teamName": "Instituto (C)",
    "debutYear": 2014,
    "fotmobPlayerImageId": 867739
  },
  {
    "name": "Jordy Caicedo",
    "position": "CF",
    "marketValueM": "0.80",
    "dateOfBirth": "1997-11-18",
    "heightCm": 185,
    "weightKg": 78,
    "preferredFoot": "Right",
    "nationality": "Ecuador",
    "teamName": "Huracán",
    "debutYear": 2018,
    "fotmobPlayerImageId": 766159
  },
  {
    "name": "Leonardo Gil",
    "position": "CM",
    "marketValueM": "1.50",
    "dateOfBirth": "1992-09-30",
    "heightCm": 170,
    "weightKg": 65,
    "preferredFoot": "Right",
    "nationality": "Argentina",
    "teamName": "Huracán",
    "debutYear": 2011,
    "fotmobPlayerImageId": 469590
  },
  {
    "name": "Bruno Barticciotto",
    "position": "RW",
    "marketValueM": "3.00",
    "dateOfBirth": "2002-01-14",
    "heightCm": 176,
    "weightKg": 68,
    "preferredFoot": "Right",
    "nationality": "Chile",
    "teamName": "Huracán",
    "debutYear": 2022,
    "fotmobPlayerImageId": 1128929
  },
  {
    "name": "Ezequiel Cerutti",
    "position": "LW",
    "marketValueM": "1.00",
    "dateOfBirth": "1992-06-02",
    "heightCm": 180,
    "weightKg": 74,
    "preferredFoot": "Left",
    "nationality": "Argentina",
    "teamName": "San Lorenzo",
    "debutYear": 2011,
    "fotmobPlayerImageId": 469593
  },
  {
    "name": "Luciano Vietto",
    "position": "CF",
    "marketValueM": "1.50",
    "dateOfBirth": "1993-12-05",
    "heightCm": 175,
    "weightKg": 70,
    "preferredFoot": "Left",
    "nationality": "Argentina",
    "teamName": "San Lorenzo",
    "debutYear": 2012,
    "fotmobPlayerImageId": 294003
  },
  {
    "name": "Alexis Cuello",
    "position": "RW",
    "marketValueM": "3.50",
    "dateOfBirth": "2001-03-25",
    "heightCm": 173,
    "weightKg": 67,
    "preferredFoot": "Left",
    "nationality": "Argentina",
    "teamName": "San Lorenzo",
    "debutYear": 2020,
    "fotmobPlayerImageId": 989370
  },
  {
    "name": "Lautaro Acosta",
    "position": "LW",
    "marketValueM": "1.50",
    "dateOfBirth": "1992-12-27",
    "heightCm": 167,
    "weightKg": 65,
    "preferredFoot": "Left",
    "nationality": "Argentina",
    "teamName": "Lanús",
    "debutYear": 2011,
    "fotmobPlayerImageId": 46295
  },
  {
    "name": "Julio Soler",
    "position": "CM",
    "marketValueM": "4.00",
    "dateOfBirth": "2001-10-05",
    "heightCm": 179,
    "weightKg": 73,
    "preferredFoot": "Right",
    "nationality": "Argentina",
    "teamName": "Lanús",
    "debutYear": 2020,
    "fotmobPlayerImageId": 1358655
  },
  {
    "name": "Matías Rojas",
    "position": "CAM",
    "marketValueM": "5.00",
    "dateOfBirth": "1997-07-22",
    "heightCm": 176,
    "weightKg": 71,
    "preferredFoot": "Right",
    "nationality": "Paraguay",
    "teamName": "Defensa y Justicia",
    "debutYear": 2017,
    "fotmobPlayerImageId": 623641
  },
  {
    "name": "Nicolás Palavecino",
    "position": "CAM",
    "marketValueM": "3.50",
    "dateOfBirth": "1997-04-25",
    "heightCm": 177,
    "weightKg": 72,
    "preferredFoot": "Left",
    "nationality": "Argentina",
    "teamName": "Defensa y Justicia",
    "debutYear": 2016,
    "fotmobPlayerImageId": 1280806
  },
  {
    "name": "Gustavo Del Prete",
    "position": "CF",
    "marketValueM": "3.00",
    "dateOfBirth": "1997-04-04",
    "heightCm": 181,
    "weightKg": 77,
    "preferredFoot": "Right",
    "nationality": "Argentina",
    "teamName": "Estudiantes (LP)",
    "debutYear": 2018,
    "fotmobPlayerImageId": 848182
  },
  {
    "name": "Javier Altamirano",
    "position": "CM",
    "marketValueM": "3.50",
    "dateOfBirth": "1999-08-21",
    "heightCm": 173,
    "weightKg": 68,
    "preferredFoot": "Left",
    "nationality": "Chile",
    "teamName": "Estudiantes (LP)",
    "debutYear": 2021,
    "fotmobPlayerImageId": 842894
  },
  {
    "name": "Adrián Martínez",
    "position": "CF",
    "marketValueM": "4.50",
    "dateOfBirth": "1997-07-04",
    "heightCm": 180,
    "weightKg": 76,
    "preferredFoot": "Right",
    "nationality": "Argentina",
    "teamName": "Rosario Central",
    "debutYear": 2018,
    "fotmobPlayerImageId": 882933
  },
  {
    "name": "Ignacio Malcorra",
    "position": "CM",
    "marketValueM": "2.00",
    "dateOfBirth": "1993-12-07",
    "heightCm": 183,
    "weightKg": 77,
    "preferredFoot": "Right",
    "nationality": "Argentina",
    "teamName": "Rosario Central",
    "debutYear": 2013,
    "fotmobPlayerImageId": 362229
  },
  {
    "name": "Tomás Pérez",
    "position": "CM",
    "marketValueM": "3.50",
    "dateOfBirth": "1998-02-28",
    "heightCm": 176,
    "weightKg": 70,
    "preferredFoot": "Right",
    "nationality": "Argentina",
    "teamName": "Newell's Old Boys",
    "debutYear": 2017,
    "fotmobPlayerImageId": 1485764
  },
  {
    "name": "Ramiro Funes Mori",
    "position": "CB",
    "marketValueM": "1.50",
    "dateOfBirth": "1991-03-05",
    "heightCm": 188,
    "weightKg": 82,
    "preferredFoot": "Right",
    "nationality": "Argentina",
    "teamName": "Newell's Old Boys",
    "debutYear": 2009,
    "fotmobPlayerImageId": 213878
  },
  {
    "name": "Ramiro Ruiz Rodríguez",
    "position": "RW",
    "marketValueM": "3.00",
    "dateOfBirth": "1998-11-22",
    "heightCm": 172,
    "weightKg": 68,
    "preferredFoot": "Right",
    "nationality": "Argentina",
    "teamName": "Atlético Tucumán",
    "debutYear": 2018,
    "fotmobPlayerImageId": 939335
  },
  {
    "name": "Alan Lescano",
    "position": "CAM",
    "marketValueM": "5.00",
    "dateOfBirth": "2002-01-22",
    "heightCm": 175,
    "weightKg": 69,
    "preferredFoot": "Left",
    "nationality": "Argentina",
    "teamName": "Argentinos Juniors",
    "debutYear": 2021,
    "fotmobPlayerImageId": 1342579
  },
  {
    "name": "Cecilio Domínguez",
    "position": "RW",
    "marketValueM": "3.00",
    "dateOfBirth": "1995-04-27",
    "heightCm": 167,
    "weightKg": 64,
    "preferredFoot": "Left",
    "nationality": "Paraguay",
    "teamName": "Argentinos Juniors",
    "debutYear": 2014,
    "fotmobPlayerImageId": 301391
  },
  {
    "name": "Braian Cufré",
    "position": "LB",
    "marketValueM": "4.00",
    "dateOfBirth": "1997-07-05",
    "heightCm": 178,
    "weightKg": 74,
    "preferredFoot": "Left",
    "nationality": "Argentina",
    "teamName": "Vélez Sarsfield",
    "debutYear": 2018,
    "fotmobPlayerImageId": 684991
  },
  {
    "name": "Lucas Janson",
    "position": "LW",
    "marketValueM": "2.50",
    "dateOfBirth": "1993-04-04",
    "heightCm": 178,
    "weightKg": 74,
    "preferredFoot": "Left",
    "nationality": "Argentina",
    "teamName": "Vélez Sarsfield",
    "debutYear": 2013,
    "fotmobPlayerImageId": 360797
  },
  {
    "name": "Maximiliano Coronel",
    "position": "SS",
    "marketValueM": "2.50",
    "dateOfBirth": "2000-05-07",
    "heightCm": 178,
    "weightKg": 72,
    "preferredFoot": "Right",
    "nationality": "Argentina",
    "teamName": "Gimnasia (LP)",
    "debutYear": 2020,
    "fotmobPlayerImageId": 182600
  },
  {
    "name": "Fabián Noguera",
    "position": "CB",
    "marketValueM": "2.00",
    "dateOfBirth": "1997-11-10",
    "heightCm": 185,
    "weightKg": 80,
    "preferredFoot": "Right",
    "nationality": "Argentina",
    "teamName": "Banfield",
    "debutYear": 2017,
    "fotmobPlayerImageId": 529208
  },
  {
    "name": "Adrián Spörle",
    "position": "LB",
    "marketValueM": "4.00",
    "dateOfBirth": "1998-03-19",
    "heightCm": 179,
    "weightKg": 72,
    "preferredFoot": "Left",
    "nationality": "Argentina",
    "teamName": "Banfield",
    "debutYear": 2018,
    "fotmobPlayerImageId": 743009
  },
  {
    "name": "Gastón Hernández",
    "position": "CM",
    "marketValueM": "2.00",
    "dateOfBirth": "1999-03-19",
    "heightCm": 177,
    "weightKg": 72,
    "preferredFoot": "Right",
    "nationality": "Argentina",
    "teamName": "Platense",
    "debutYear": 2019,
    "fotmobPlayerImageId": 1144961
  },
  {
    "name": "Jonathan Fabbro",
    "position": "LW",
    "marketValueM": "1.00",
    "dateOfBirth": "1993-12-07",
    "heightCm": 174,
    "weightKg": 70,
    "preferredFoot": "Left",
    "nationality": "Argentina",
    "teamName": "Platense",
    "debutYear": 2013,
    "fotmobPlayerImageId": 96815
  }
] as const satisfies ReadonlyArray<PlayerSeedTemplate>;
